/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as AuthenticatedChamadosIndexRouteImport } from './routes/_authenticated/chamados.index'
import { Route as AuthenticatedChamadosNovoRouteImport } from './routes/_authenticated/chamados.novo'
import { Route as AuthenticatedChamadosIdRouteImport } from './routes/_authenticated/chamados.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtendimentoRoute =
  AuthenticatedAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChamadosIndexRoute =
  AuthenticatedChamadosIndexRouteImport.update({
    id: '/chamados/',
    path: '/chamados/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChamadosNovoRoute =
  AuthenticatedChamadosNovoRouteImport.update({
    id: '/chamados/novo',
    path: '/chamados/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChamadosIdRoute = AuthenticatedChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/chamados/': typeof AuthenticatedChamadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/chamados': typeof AuthenticatedChamadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/_authenticated/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/_authenticated/chamados/': typeof AuthenticatedChamadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/atendimento'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/chamados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/atendimento'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/chamados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/atendimento'
    | '/_authenticated/chamados/$id'
    | '/_authenticated/chamados/novo'
    | '/_authenticated/chamados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chamados/': {
      id: '/_authenticated/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof AuthenticatedChamadosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chamados/novo': {
      id: '/_authenticated/chamados/novo'
      path: '/chamados/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof AuthenticatedChamadosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chamados/$id': {
      id: '/_authenticated/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof AuthenticatedChamadosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedChamadosIdRoute: typeof AuthenticatedChamadosIdRoute
  AuthenticatedChamadosNovoRoute: typeof AuthenticatedChamadosNovoRoute
  AuthenticatedChamadosIndexRoute: typeof AuthenticatedChamadosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedChamadosIdRoute: AuthenticatedChamadosIdRoute,
  AuthenticatedChamadosNovoRoute: AuthenticatedChamadosNovoRoute,
  AuthenticatedChamadosIndexRoute: AuthenticatedChamadosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
